<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<DebugType>none</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Il2CppInteropVerbose>true</Il2CppInteropVerbose>
		<Optimize>True</Optimize>
		<VersionPrefix>1.0.1</VersionPrefix>
		<Description>Standalone /endgame and /endmeeting host commands for Among Us</Description>
		<Authors>Katzklaw</Authors>
		<AssemblyName>Ender</AssemblyName>
		<RootNamespace>Ender</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AmongUs.GameLibs.Steam" Version="2026.6.5" />
		<PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" PrivateAssets="all" ExcludeAssets="runtime" />
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" ExcludeAssets="runtime;native" />
	</ItemGroup>
</Project>